// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: protos/wikiTextParser.proto

package wikiTextParser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WikiTextParserService_GetWikiTextParse_FullMethodName = "/wikiTextParser.WikiTextParserService/GetWikiTextParse"
)

// WikiTextParserServiceClient is the client API for WikiTextParserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WikiTextParserServiceClient interface {
	GetWikiTextParse(ctx context.Context, in *WikiText, opts ...grpc.CallOption) (*JsonText, error)
}

type wikiTextParserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWikiTextParserServiceClient(cc grpc.ClientConnInterface) WikiTextParserServiceClient {
	return &wikiTextParserServiceClient{cc}
}

func (c *wikiTextParserServiceClient) GetWikiTextParse(ctx context.Context, in *WikiText, opts ...grpc.CallOption) (*JsonText, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonText)
	err := c.cc.Invoke(ctx, WikiTextParserService_GetWikiTextParse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WikiTextParserServiceServer is the server API for WikiTextParserService service.
// All implementations must embed UnimplementedWikiTextParserServiceServer
// for forward compatibility.
type WikiTextParserServiceServer interface {
	GetWikiTextParse(context.Context, *WikiText) (*JsonText, error)
	mustEmbedUnimplementedWikiTextParserServiceServer()
}

// UnimplementedWikiTextParserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWikiTextParserServiceServer struct{}

func (UnimplementedWikiTextParserServiceServer) GetWikiTextParse(context.Context, *WikiText) (*JsonText, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWikiTextParse not implemented")
}
func (UnimplementedWikiTextParserServiceServer) mustEmbedUnimplementedWikiTextParserServiceServer() {}
func (UnimplementedWikiTextParserServiceServer) testEmbeddedByValue()                               {}

// UnsafeWikiTextParserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WikiTextParserServiceServer will
// result in compilation errors.
type UnsafeWikiTextParserServiceServer interface {
	mustEmbedUnimplementedWikiTextParserServiceServer()
}

func RegisterWikiTextParserServiceServer(s grpc.ServiceRegistrar, srv WikiTextParserServiceServer) {
	// If the following call pancis, it indicates UnimplementedWikiTextParserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WikiTextParserService_ServiceDesc, srv)
}

func _WikiTextParserService_GetWikiTextParse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WikiText)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiTextParserServiceServer).GetWikiTextParse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiTextParserService_GetWikiTextParse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiTextParserServiceServer).GetWikiTextParse(ctx, req.(*WikiText))
	}
	return interceptor(ctx, in, info, handler)
}

// WikiTextParserService_ServiceDesc is the grpc.ServiceDesc for WikiTextParserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WikiTextParserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wikiTextParser.WikiTextParserService",
	HandlerType: (*WikiTextParserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWikiTextParse",
			Handler:    _WikiTextParserService_GetWikiTextParse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/wikiTextParser.proto",
}
