// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: protos/wikiTextParser.proto

package wikiTextParser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WikiText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *WikiText) Reset() {
	*x = WikiText{}
	mi := &file_protos_wikiTextParser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WikiText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WikiText) ProtoMessage() {}

func (x *WikiText) ProtoReflect() protoreflect.Message {
	mi := &file_protos_wikiTextParser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WikiText.ProtoReflect.Descriptor instead.
func (*WikiText) Descriptor() ([]byte, []int) {
	return file_protos_wikiTextParser_proto_rawDescGZIP(), []int{0}
}

func (x *WikiText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type JsonText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *JsonText) Reset() {
	*x = JsonText{}
	mi := &file_protos_wikiTextParser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonText) ProtoMessage() {}

func (x *JsonText) ProtoReflect() protoreflect.Message {
	mi := &file_protos_wikiTextParser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonText.ProtoReflect.Descriptor instead.
func (*JsonText) Descriptor() ([]byte, []int) {
	return file_protos_wikiTextParser_proto_rawDescGZIP(), []int{1}
}

func (x *JsonText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_protos_wikiTextParser_proto protoreflect.FileDescriptor

var file_protos_wikiTextParser_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x77, 0x69, 0x6b, 0x69, 0x54, 0x65, 0x78,
	0x74, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x77,
	0x69, 0x6b, 0x69, 0x54, 0x65, 0x78, 0x74, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x22, 0x1e, 0x0a,
	0x08, 0x57, 0x69, 0x6b, 0x69, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x1e, 0x0a,
	0x08, 0x4a, 0x73, 0x6f, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x32, 0x5f, 0x0a,
	0x15, 0x57, 0x69, 0x6b, 0x69, 0x54, 0x65, 0x78, 0x74, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x57, 0x69, 0x6b,
	0x69, 0x54, 0x65, 0x78, 0x74, 0x50, 0x61, 0x72, 0x73, 0x65, 0x12, 0x18, 0x2e, 0x77, 0x69, 0x6b,
	0x69, 0x54, 0x65, 0x78, 0x74, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x57, 0x69, 0x6b, 0x69,
	0x54, 0x65, 0x78, 0x74, 0x1a, 0x18, 0x2e, 0x77, 0x69, 0x6b, 0x69, 0x54, 0x65, 0x78, 0x74, 0x50,
	0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x42, 0x20,
	0x5a, 0x1e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x77, 0x69, 0x6b, 0x69, 0x54, 0x65, 0x78, 0x74, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_wikiTextParser_proto_rawDescOnce sync.Once
	file_protos_wikiTextParser_proto_rawDescData = file_protos_wikiTextParser_proto_rawDesc
)

func file_protos_wikiTextParser_proto_rawDescGZIP() []byte {
	file_protos_wikiTextParser_proto_rawDescOnce.Do(func() {
		file_protos_wikiTextParser_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_wikiTextParser_proto_rawDescData)
	})
	return file_protos_wikiTextParser_proto_rawDescData
}

var file_protos_wikiTextParser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_wikiTextParser_proto_goTypes = []any{
	(*WikiText)(nil), // 0: wikiTextParser.WikiText
	(*JsonText)(nil), // 1: wikiTextParser.JsonText
}
var file_protos_wikiTextParser_proto_depIdxs = []int32{
	0, // 0: wikiTextParser.WikiTextParserService.GetWikiTextParse:input_type -> wikiTextParser.WikiText
	1, // 1: wikiTextParser.WikiTextParserService.GetWikiTextParse:output_type -> wikiTextParser.JsonText
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_wikiTextParser_proto_init() }
func file_protos_wikiTextParser_proto_init() {
	if File_protos_wikiTextParser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_wikiTextParser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_wikiTextParser_proto_goTypes,
		DependencyIndexes: file_protos_wikiTextParser_proto_depIdxs,
		MessageInfos:      file_protos_wikiTextParser_proto_msgTypes,
	}.Build()
	File_protos_wikiTextParser_proto = out.File
	file_protos_wikiTextParser_proto_rawDesc = nil
	file_protos_wikiTextParser_proto_goTypes = nil
	file_protos_wikiTextParser_proto_depIdxs = nil
}
